name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa

      - name: Deploy to Azure Server
        env:
          AZURE_HOST: ${{ secrets.AZURE_HOST }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
        run: |
          ssh $AZURE_USERNAME@$AZURE_HOST << 'EOF'
          
            # Stop and remove existing container if running
            existing_container_id=\$(docker ps -q --filter "name=blog-nextjs")
            if [ ! -z "\$existing_container_id" ]; then
              docker stop \$existing_container_id
              docker rm \$existing_container_id
            fi
          
            # Remove any existing image to avoid conflicts
            existing_image_id=\$(docker images -q blog-nextjs)
            if [ ! -z "\$existing_image_id" ]; then
              docker rmi \$existing_image_id
            fi
          
            # Pull latest code and build
            cd new_blog/blog
            git pull
            npm install
            npm run build
          
            # Build and run new Docker container
            docker build -t blog-nextjs .
            docker run -d -p 3000:3000 --name blog-nextjs blog-nextjs
          EOF
