name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.AZURE_HOST }} >> ~/.ssh/known_hosts
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Copy environment configuration to server
        env:
          AZURE_HOST: ${{ secrets.AZURE_HOST }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          ENV_CONFIG: ${{ vars.ENV_CONFIG }}
        run: |
          echo "${{ env.ENV_CONFIG }}" | ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $AZURE_USERNAME@$AZURE_HOST 'cat > new_blog/blog/.env'

      - name: Update project
        env:
          AZURE_HOST: ${{ secrets.AZURE_HOST }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $AZURE_USERNAME@$AZURE_HOST << 'EOF'
            # Add GitHub to known_hosts
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts

            cd new_blog/blog

            # Ensure the correct branch is checked out
            git checkout main

            # Set remote URL to use SSH
            git remote set-url origin git@github.com:Hearify/blog.git

            # Verify remote URL and branch tracking
            echo "Remote URL:"
            git remote -v

            echo "Branch tracking information:"
            git branch -vv

            # Force fetch the latest changes
            git fetch origin

            # Pull the latest changes
            git pull origin main

            # Debugging: Show the state after pull
            echo "State after git pull:"
            git branch -v

            npm install
            npm run build

            chmod +x deploy.sh
            ./deploy.sh
          EOF
