name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.AZURE_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into server and update project
        env:
          AZURE_HOST: ${{ secrets.AZURE_HOST }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $AZURE_USERNAME@$AZURE_HOST << 'EOF'
            cd /home/$AZURE_USERNAME/new_blog/blog
            git pull
            npm install
            npm run build
          EOF

      - name: Copy environment configuration to server
        env:
          AZURE_HOST: ${{ secrets.AZURE_HOST }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          ENV_CONFIG: ${{ vars.ENV_CONFIG }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $AZURE_USERNAME@$AZURE_HOST 'echo "${{ secrets.ENV_CONFIG }}" > /home/$AZURE_USERNAME/new_blog/blog/.env'

      - name: Execute deploy script on server
        env:
          AZURE_HOST: ${{ secrets.AZURE_HOST }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $AZURE_USERNAME@$AZURE_HOST << 'EOF'
            cd /home/$AZURE_USERNAME/new_blog/blog
            chmod +x deploy.sh
            ./deploy.sh
          EOF
